/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 painting_opt.glb 
Author: NANO (https://sketchfab.com/NanoGames)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/zalipie-house-of-painters-slavic-interior-3908d8b3ef3c4e98a6689b90a1f0ecf3
Title: Zalipie | House of Painters | Slavic Interior
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Painting_Room(props) {
  const { nodes, materials } = useGLTF('/models/painting_opt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.interior_Material_u1_v1} position={[2.54, -0.677, 11.417]} rotation={[0, -1.566, -Math.PI]} scale={23.021} />
    </group>
  )
}

useGLTF.preload('/models/painting_opt.glb')
