/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 window.glb 
Author: Martin Mikulić (https://sketchfab.com/martin_mikulic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/window-cleaning-10654447a8054297a9361a80490a9317
Title: Window cleaning
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WindowModel(props) {
  const { nodes, materials } = useGLTF('/models/window.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.default_PackedMaterial0mat_0.geometry} material={materials.PackedMaterial0mat} position={[-6.155, 1.99, 34.598]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Bottoms_PackedMaterial1mat_0.geometry} material={materials.PackedMaterial1mat} position={[-6.155, 1.99, 34.598]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Body_PackedMaterial0mat_0.geometry} material={materials.PackedMaterial0mat} position={[-6.155, 1.99, 34.598]} rotation={[2.094, 0, -Math.PI]} />
      <mesh geometry={nodes.Tops_PackedMaterial1mat_0.geometry} material={materials.PackedMaterial1mat} position={[-6.155, 1.99, 34.598]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Eyelashes_PackedMaterial0mat_0.geometry} material={materials.PackedMaterial0mat} position={[-6.155, 1.99, 34.598]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Shoes_PackedMaterial1mat_0.geometry} material={materials.PackedMaterial1mat} position={[-6.155, 1.99, 34.598]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Cylinder001_prozorCistac_0.geometry} material={materials.prozorCistac} position={[-1.796, 87.984, -9.675]} rotation={[-1.33, -0.273, 0.071]} />
      <mesh geometry={nodes.kapa_Material_0.geometry} material={materials.Material} position={[8.011, 169.49, 21.923]} rotation={[-2.302, -0.079, -0.037]} />
      <mesh geometry={nodes.CC_Game_Eye_Ga_Eye_0.geometry} material={materials.Ga_Eye} position={[128.529, 0, -88.473]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.CC_Game_Teeth_Ga_Teeth_0.geometry} material={materials.Ga_Teeth} position={[128.529, 0, -88.473]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.CC_Game_Tongue_Ga_Skin_Body_0.geometry} material={materials.Ga_Skin_Body} position={[128.529, 0, -88.473]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Hair_embed_hair_male_0.geometry} material={materials.embed_hair_male} position={[128.529, 0, -88.473]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.CC_Game_Body_Ga_Skin_Body_0.geometry} material={materials.Ga_Skin_Body} position={[21.254, 0, -88.473]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/window.glb')
